# Generated by Django 3.0.4 on 2020-05-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('password', models.CharField(default='None', max_length=1000)),
                ('profilePic', models.ImageField(null=True, upload_to='')),
                ('isActive', models.BooleanField(null=True)),
            ],
        ),
    ]
